### ISSUE TITLE
Enable sandboxing/multi-user mode

### ISSUE THREAD

**Issue by thoughtpolice** [cachix/install-nix-action#11]
The current installation step for the action just installs Nix in single-user mode, not multi-user mode, which is a requirement for sandboxing. Sandboxing has been enabled by default for multi-user, on both Darwin and Linux for a while provided you pass `--daemon` to the installer.

It would be nice if this could be enabled, or otherwise noted why that might be technically infeasible, because otherwise host impurities in the (Ubuntu?) distro can leak into the build steps. On top of that, it can probably introduce other strange failures, since we don't test it -- many packages in Nixpkgs at least fail without sandboxing enabled because they get confused by host system features (they will see something in `/etc/os-release` or `/dev` and make a decision we otherwise wouldn't encounter, and the build steps change. The kernel packages are the most obvious example of a package that don't build without sandboxing but there are certainly many many others).

It does seem like GitHub actions supports passwordless `sudo` for virtual Ubuntu runners ([docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#administrative-privileges-of-github-hosted-runners)), so this should be easy.

Actually, the most annoying part might be the fact that I don't think the script has a "Say yes to every prompt" option since daemon mode installation is interactive, but I think we can easily fix it a la `yes | sh /path/to/install`

**Comment by thoughtpolice** [comment]
As a historical note, the old version of GitHub Actions (HCL workflows) used Docker containers, so I used [lnl7/nix-docker](https://github.com/LnL7/nix-docker) to run builds previously, e.g. for [rv32-sail](https://github.com/thoughtpolice/rv32-sail).

That container *also* does not enable sandboxing for more obvious reasons (yay systemd in docker), but it is also much, much more "purified" than a traditional Ubuntu/Alpine container is, and closer to NixOS, so I was less worried about image impurities. So strictly speaking this would be a real improvement over the prior workflow, in a way that can't be hacked around!

**Comment by domenkozar** [comment]
Sadly multi-user is written in very defensive mode, so that we can't populate `/etc/nix` or `/nix` (which is needed for macOS).

Getting an error like 

```
There are some relics of a previous installation of Nix at /etc/nix, and
this scripts assumes Nix is _not_ yet installed. Please delete the old
Nix installation and start again.
```

This has been raised upstream, for example https://github.com/NixOS/nix/issues/2407

**Comment by thoughtpolice** [comment]
I might be missing something, but why not just run another script that does the necessary setup after the installation? There's nothing wrong with modifying `nix.conf` *after* the installer completes its work, is there? Or does the mere act of bootstrapping during the installation cause segfaults due to http2?

If so, I think we could still do this by getting clever with the script (for example, by patching `--no-http2` into the bootstrap phase.) But there are a number of other possible fixes, too...

**Comment by domenkozar** [comment]
I've gotten past that, ubuntu seems to work.

macOS is stubborn due to https://github.com/NixOS/nix/blob/master/scripts/install-multi-user.sh#L219 calling sudo, which doesn't propagate my environment variables to Nix.

Going to continue later.

**Comment by dtzWill** [comment]
(!!!)

Building paths without sandbox enabled and pushing those to cachix
is a _big_ problem! I didn't even think to check, as why would anyone
**share** paths built in such an impure environment??

I see there's a sandbox branch, fingers crossed and thank you :).
If it ends up that this can't be resolved soon,
please consider adding giant warning to folks looking at this :/.

Yet again I wish there was a flag to tell Nix to refuse to cooperate
with any builder that either doesn't support sandbox builds
or has them disabled.

Or at least sign them with a different key so they can be
tracked differently-- untangling propagated paths and
everything that might have built using them
(while avoiding mass rebuilds) is not an easy task.

Anyway, thank you for filing the issue and I just wanted to pipe up
and let folks know this is important to some users like me O:).

Happily I haven't moved to using this
(although I look forward to doing so)
for anything driving giant package sets
so I think all is well... but close call :).

**Comment by thoughtpolice** [comment]
> Yet again I wish there was a flag to tell Nix to refuse to cooperate
with any builder that either doesn't support sandbox builds
or has them disabled.

It's unrelated to this ticket but personally I would prefer to see single-user mode completely removed from the installer unless you provide a gigantic `--this-is-a-development-build-that-is-incredibly-beta-and-single-user-because-of-platform-deficiencies` and you have to provide that exact flag to enable it and there is no other way.

**Comment by domenkozar** [comment]
> Building paths without sandbox enabled and pushing those to cachix
is a _big_ problem! I didn't even think to check, as why would anyone
**share** paths built in such an impure environment??

If you're only using cachix as a speedup of github actions that a reasonable use case and it's sufficient to avoid sandbox.

Not saying that sandbox is not superior, but that there are a few cases where you can avoid it (with some cost).

Either way, seems like this is very close to done :)

**Comment by domenkozar** [comment]
I've fixed the sudo issue. Now stuck at 

```
error: cannot open connection to remote store 'daemon': the path '/nix' is a symlink; this is not allowed for the Nix store and its parent directories
```

Seems like we need to set the envvar also for the daemon.

**Comment by domenkozar** [comment]
https://github.com/cachix/install-nix-action/pull/12 is ready for review.

**Comment by thoughtpolice** [comment]
Amazing, thank you @domenkozar!

**Comment by dtzWill** [comment]
Thank you!

Hmm, is this ready? ... If so, any hints on how to give it a go?

I see there's a branch `releases/v6` but no tagged release or whatever it takes to make it available :).
No worries if there's not a good way to use it just yet, I see the Darwin users are making things slow which indeed seems good to get fixed :).

**Comment by domenkozar** [comment]
Seems like sandbox doesn't yet work on macOS: https://github.com/cachix/install-nix-action/issues/15

so v6 will only ship sandbox for linux.
