### ISSUE TITLE
flakes don't seem to be enabled by default

### ISSUE THREAD

**Issue by johnrichardrinehart** [cachix/install-nix-action#110]
My understanding is that #103 enabled support for flake commands (`nix build`, `nix develop`, etc.), by default. But, I tried to use a build after #103, I think, and `flake` support wasn't enabled by default:

https://github.com/johnrichardrinehart/nix/actions/runs/1443980922/workflow

I patched it by adding the `experimental-features` line, but I was hoping this wouldn't be necessary:

https://github.com/johnrichardrinehart/nix/actions/runs/1443993664/workflow#L21

**Comment by johnrichardrinehart** [comment]
My bad. I was pinned to an old version. I pointed to 74ef8ad2cfb373eef5eb62483d242712e1e1ac07 and everything seems fine, now.

Let's bump the semver :) !!! ❤️ 

Thanks for your work on this project!

**Comment by domenkozar** [comment]
Released v15!
