### ISSUE TITLE
Transient errors shouldn't cause the action to succeed

### ISSUE THREAD

**Issue by flokli** [cachix/install-nix-action#113]
I stumbled over a GH Action that couldn't find `nix-env`.

Digging further up, I saw `cachix/install-nix-action@v14.1` had a transient error, did retry 5 times, and then ultimately failed.

However, it didn't exit with a nonzero exit status:

![image](https://user-images.githubusercontent.com/183879/142274154-64b50f6a-2ae1-4b99-966a-54ea4901495b.png)

**Comment by flokli** [comment]
This is v14.1, not v15, so I didn't check if this still occurs with v15, or whether https://github.com/cachix/install-nix-action/pull/105 fixed it.

**Comment by domenkozar** [comment]
v15 should fix this with --fail passed to curl and it tries indefinitely :)

**Comment by flokli** [comment]
Retrying indefinitely isn't that nice either - I'm not sure what the timeouts are, but we should probably fail before burning hours of CI minutes until GH Actions eventually times out…

**Comment by domenkozar** [comment]
Nix installation URL shouldn't be down for that long. 

if it is, it would be a rare event and I'd rather burn a few dollars then waste human time restarting builds.
