### ISSUE TITLE
Make curl less noisy 

### ISSUE THREAD

**Issue by SuperSandro2000** [cachix/install-nix-action#126]
Right now curl logs a bunch of TLS and HTTP debugging things which are most of the time just noise. I think the `-v` [here](https://github.com/cachix/install-nix-action/blob/master/lib/install-nix.sh#L59) should be removed. What do you think?

**Comment by domenkozar** [comment]
There used to be issues with nixos.org and then having silent curl makes it painful to debug what's going on.
