### ISSUE TITLE
slow installation on macos

### ISSUE THREAD

**Issue by domenkozar** [cachix/install-nix-action#13]
NIX_USER_COUNT is set to 32, which is about 30 users too many. Setting up a user on macos is slow (~1s).

**Comment by adrian-gierakowski** [comment]
yeah, it takes 1.5 minutes to run the action on MacOs (vs 15s on Ubuntu). It prompted me to open this: https://github.com/actions/virtual-environments/issues/376

**Comment by domenkozar** [comment]
I think I can get this down to ~20s.

- [ ] [Install only 2 users instead of 32](https://github.com/NixOS/nix/pull/3375)
- [ ] don't provide channel by default
- [ ] ability to pass nix.conf to installer to avoid restarting the daemon

**Comment by domenkozar** [comment]
Happy to report that with Nix 2.3.5 and not adding a channel, Linux installs in ~5s and macOS on ~20: https://github.com/cachix/install-nix-action/pull/33/checks?check_run_id=712804392
