### ISSUE TITLE
How to sponsor/donate?

### ISSUE THREAD

**Issue by strager** [cachix/install-nix-action#164]
My project uses install-nix-action and I would like to tip the developers. Do you permit GitHub Sponsors or any other way to contribute financially?

**Comment by domenkozar** [comment]
Yes, subscribing to Cachix is the best way to support our efforts to improve Nix.

**Comment by strager** [comment]
The [lowest-cost Cachix plan](https://www.cachix.org/pricing) is 42 USD per month, which is more than I'm willing to contribute.

**Comment by domenkozar** [comment]
The plans are aimed at companies, so for personal use the best thing you can do is to express how Cachix has helped you.
