### ISSUE TITLE
`no space left` When running multiple `nix build ...` at the same time.

### ISSUE THREAD

**Issue by dpc** [cachix/install-nix-action#173]
I'm running multiple `nix build -L ...` via GNU parallel, and they are hitting some space limit somewhere, but I just can't figure out where exactly.

I've googled and tried so many things, remouted all tmpfs mounts to increase their size and something is always wrong.

What options should I add an where to increase the respective build size capacity when using `install-nix-action`?

**Comment by sandydoo** [comment]
I would imagine you're running out of memory or space in `/tmp`. I would start by reducing the number of simultaneous builds and monitoring the resource usage of your action with https://github.com/nektos/act.

**Comment by dpc** [comment]
Thanks. I have figured it out since then.
