### ISSUE TITLE
heads-up: we have seen CI failures due to the recent `nix-2.15` bump

### ISSUE THREAD

**Issue by ggreif** [cachix/install-nix-action#175]
... that was (automatically) performed by `install-nix-action`. This probably isn't the fault of the action, rather either
- `nix-2.15` is broken in some way, or
- our `.nix` tooling is buggy (triggers some `.drv` snafu)

I would be interested to see whether others have problems too.

----------
The symptoms can be seen in https://github.com/dfinity/motoko/actions/runs/4681124992/jobs/8293314145.
We get warnings like
```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/wcdjm32sjplq2nna4j1sz70knpwfqs05-mo-ide.drv!*'
[319](https://github.com/dfinity/motoko/actions/runs/4681124992/jobs/8293314145#step:7:320)
  /nix/store/cx4059083xldbvnspcvqlx69f4fa70ff-jq-1.6-bin
[320](https://github.com/dfinity/motoko/actions/runs/4681124992/jobs/8293314145#step:7:321)
```
and the builds terminate (successfully) abnormally fast. (Of course they don't run at all.)

**Comment by Artturin** [comment]
It's a nix-build-uncached bug https://github.com/Mic92/nix-build-uncached/issues/52

**Comment by Artturin** [comment]
https://github.com/Mic92/nix-build-uncached/pull/53
