### ISSUE TITLE
Run fails on Windows

### ISSUE THREAD

**Issue by soywod** [cachix/install-nix-action#176]
Looks like the action does not even start on a Windows machine:

```
Run cachix/install-nix-action@v20
Run D:\a\_actions\cachix\install-nix-action\v20/install-nix.sh
D:\a\_temp\9deaaf18-4fdd-4[6](https://github.com/soywod/comodoro/actions/runs/4700542825/jobs/8335371841#step:5:7)bb-8a67-a4fcdd4ad6ae.sh: line 1: D:a_actionscachixinstall-nix-actionv20/install-nix.sh: No such file or directory
Error: Process completed with exit code 127.
```

Full logs available [here](https://github.com/soywod/comodoro/actions/runs/4700542825/jobs/8335371841).

**Comment by sandydoo** [comment]
@soywod, Nix doesn't support Windows and neither does its installer.

If you want to build Windows executables with Nix, you'll have to cross-compile from Linux.

**Comment by soywod** [comment]
> If you want to build Windows executables with Nix, you'll have to cross-compile from Linux.

Understood, thank you for you quick reply!
