### ISSUE TITLE
Document how and if to run NixOS tests

### ISSUE THREAD

**Issue by 573** [cachix/install-nix-action#19]
I am getting an

> error: a 'x86_64-linux' with features {kvm, nixos-test} is required to build '/nix/store/1rq4j0hk5g5p3917q13qzpa7rj19r61s-vm-test-run-redis.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test}

when running cachix-action after install-nix-action against https://github.com/573/nix-github-integration-tests.

Would I need to add the line system-features = nixos-test to the configuration and how ?

I have tried and [failed](https://github.com/573/nix-github-integration-tests/pull/5/checks?check_run_id=375328498#step:4:13) to add the following line to my actions yml already:

    sudo sh -c echo system-features = nixos-test >> /etc/nix/nix.conf

[Original question](https://github.com/cachix/cachix-action/issues/26#issue-545629363)

**Comment by 573** [comment]
By adding the lines `mkdir -p ~/.config/nix` and `echo system-features = kvm nixos-test >> ~/.config/nix/nix.conf` ([ref.](https://github.com/573/nix-github-integration-tests/commit/a1c890823dd4546ad66a64c1d1b21c2c3daef595#diff-90829e76e906f1c73140c7ded7e1b268R14)) to a run section of the action yml file integration tests are enabled.

**Comment by domenkozar** [comment]
Those tests will run very slowly since there's no hardware acceleration support.

**Comment by 573** [comment]
@domenkozar thanks for pointing this out!

I recently discovered that I chose the wrong approach here as nixosTests really seem to be targeting service to service communication as I understand it now.

[Luckily](https://github.com/573/shorturls/commit/a34b28e98639607bd0590cd3ec76ef719ba2cc05) I have figured out ([not me TBH](https://kuznero.com/post/linux/haskell-project-structure-in-nixos/) and yes got the basic idea from [here](https://discourse.nixos.org/t/running-tests-faster-raw-not-within-qemu/5396)) how to do integration testing.

**Comment by domenkozar** [comment]
Yes, I should document this.

**Comment by domenkozar** [comment]
Documented!
