### ISSUE TITLE
Nix cannot be installed on subsequent runs on hosted runners

### ISSUE THREAD

**Issue by peperunas** [cachix/install-nix-action#191]
I switched to a self-hosted runner from `ubuntu-latest` and only the first action was able to complete successfully. The followings fail at installing Nix as it results already installed from the previous run.

It seems the installation in the self-hosted runner is not sandboxed, i.e., Nix is not installed on a per-action basis / contained.

Any hints?

Thank you!

**Comment by sandydoo** [comment]
Could you paste the error you're seeing?

**Comment by peperunas** [comment]
Hello,

Unfortunately, I checked the logs, but they expired and are unavailable. I have re-switched to the hosted Github Actions as a workaround for now.

If you have any pointers, I would gladly try to troubleshoot.

Best,
Giulio

**Comment by vbgl** [comment]
I’ve just witnessed a similar situation: first run on a self-hosted runner went nicely, the following one failed with:

>  ~~> Checking for artifacts of previous installs
  Before I try to install, I'll check for signs Nix already is or has
  been installed on this system.
  
>  ---- oh no! --------------------------------------------------------------------
  I back up shell profile/rc scripts before I add Nix to them.
  I need to back up /etc/bash.bashrc to /etc/bash.bashrc.backup-before-nix,
  but the latter already exists.

**Comment by vbgl** [comment]
But it seems to have been fixed already: with version 25 of this action, in a similar setting I get:

> Aborting: Nix is already installed at /nix/var/nix/profiles/default/bin/nix

**Comment by sandydoo** [comment]
> It seems the installation in the self-hosted runner is not sandboxed, i.e., Nix is not installed on a per-action basis / contained.

This is a common misconception with self-hosted runners. There's no sandboxing by default. GitHub leaves it up to you to figure out how to set this up.

> I’ve just witnessed a similar situation: first run on a self-hosted runner went nicely, the following one failed with...
>
> I still see this with version 25

The action checks whether `nix` is in the PATH. If Nix is already installed on your runner, but the action can't find it, then there's likely something wrong with your environment. You may have to modify your runner to make this work.

A lot of this was already discussed in #98, so I'm closing this as a duplicate.
