### ISSUE TITLE
Nix is not usable on self-hosted runners

### ISSUE THREAD

**Issue by jheidbrink** [cachix/install-nix-action#195]
We deploy self-hosted runners to EKS using the actions-runner-controller Helm chart. There is usually exactly one runner pod. When I initially tried `install-nix-action`, it worked without issues. After manually deleting the runner pod and waiting until a fresh pod is deployed, `nix-install-action` succeeds, but Nix is not usable.

The following workflow code
```
      - uses: cachix/install-nix-action@v22
      - name: Verify Nix installation
        run: nix-shell -p nix-info --run "nix-info -m"
```

leads to the following error (in the "Verify Nix installation" step):
```
Run nix-shell -p nix-info --run "nix-info -m"
  nix-shell -p nix-info --run "nix-info -m"
  shell: /usr/bin/bash -e {0}
error:
       … <borked>

         at «none»:0: (source not available)

       … while calling the 'import' builtin

         at «string»:1:18:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                  ^

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)
Error: Process completed with exit code 1.
```

**Comment by jheidbrink** [comment]
Looking at `~/.nix-defexpr` I see two broken symlinks:

**Comment by jheidbrink** [comment]
The one runner pod is persisted between workflow runs, not sure if this might be a problem.

**Comment by domenkozar** [comment]
It does not set `NIX_PATH` by default, so it must have been your self-hosted runner configuration that set it?

Either way, you should be able to pass `nix_path` input to address this.

**Comment by jheidbrink** [comment]
I have no clue how it has worked if the installation doesn't set NIX_PATH ;)

When adding
```
        with:
          nix_path: nixpkgs=channel:nixos-2305
```

I get

```
Run nix-shell -p nix-info --run "nix-info -m"
  
warning: Nix search path entry 'channel:nixos-2305' cannot be downloaded, ignoring
```

and then the same error as in my initial message.

**Comment by sandydoo** [comment]
@jheidbrink, aren't you missing a period in the channel version? 

```diff
+ nix_path: nixpkgs=channel:nixos-23.05
- nix_path: nixpkgs=channel:nixos-2305
```
