### ISSUE TITLE
Default GitHub token is not valid for github.com when using GitHub Enterprise

### ISSUE THREAD

**Issue by gdw2** [cachix/install-nix-action#196]
### Expected

If I don't explicitly specify a github token, I would expect it to try to access github 'anonymously' (subject to rate limiting).  

### Actual

(From the `nix-shell-action` action which leverages the work done by install-nix-action. )

```
error:
       … while fetching the input 'github:NixOS/nixpkgs/nixpkgs-unstable'

       error: unable to download 'https://api.github.com/repos/NixOS/nixpkgs/commits/nixpkgs-unstable': HTTP error 401

       response body:

       {
         "message": "Bad credentials",
         "documentation_url": "https://docs.github.com/rest"
       }
```

### Analysis

I'd like to be able to use `install-nix-action` without a github token, but I don't think it's possible to withhold the `$GITHUB_TOKEN` from [the script](https://github.com/cachix/install-nix-action/blob/300721fe01bc8c4cf4677859b80e55154023c7d3/install-nix.sh#L31-L32).  I tried passing `GITHUB_TOKEN` as an empty string, but I think github overrides it with my actual token.

**_Since I'm using Github Enterprise, my token isn't valid for github.com, so I get the "Bad credentials" error above._**

My solution was to fork this repo, and comment out [these lines](https://github.com/cachix/install-nix-action/blob/300721fe01bc8c4cf4677859b80e55154023c7d3/install-nix.sh#L31-L32) and then it works fine for me.

**Comment by sandydoo** [comment]
We could check whether `$GITHUB_SERVER_URL` or `{{ github.server_url }}` is set to `https://github.com`. If it's not, then we don't use the default token. @gdw2 , would you be able to test this out for us if we roll out a fix?

**Comment by gdw2** [comment]
Sure

**Comment by sandydoo** [comment]
@gdw2, could you please test this [branch](https://github.com/cachix/install-nix-action/compare/fix/196) when you have the chance?

```yaml
- uses: cachix/install-nix-action@fix/196
```

**Comment by domenkozar** [comment]
@gdw2 ping :)

**Comment by gdw2** [comment]
I think it worked.  I'm getting the following message in a latter stage (using the nix-shell-action action), which means I may have to use a token after all, but that's my problem:

```
{"message":"API rate limit exceeded for XX.XX.XX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

I'd go ahead and merge this.  Thanks.
