### ISSUE TITLE
Reduce major updates

### ISSUE THREAD

**Issue by SuperSandro2000** [cachix/install-nix-action#204]
Most official actions from GitHub only do a major version upgrade when they minimum required nodejs version changes which is required to not break actions for GitHub enterprise.
I would like to see something similar for this action, that I can just use the latest version and don't get frequent updates in comparison.

Maybe a latest tag or v0 or vX could be used for that when people prefer less version bumps over stability.

**Comment by domenkozar** [comment]
I want Nix bumps to be a major breaking change because they do break and so it's better to be explicit.

**Comment by SuperSandro2000** [comment]
I have so far mindlessly merged all bump PRs I got for this action and no other action I know does so many updates.

For example the go install action allows to specify a go version range
https://github.com/actions/setup-go?tab=readme-ov-file#basic

Why not go that route to reduce churn?
