### ISSUE TITLE
Local paths in hoogle point to /opt/nix

### ISSUE THREAD

**Issue by fiadliel** [cachix/install-nix-action#21]
When hoogle documentation (I'm invoking from haskell.nix) is built with this action, the resulting hoogle database contains paths to /opt/nix instead of /nix. This is the obvious direct culprit 😢 

I've only validated this on the MacOS platform, so I'm not certain if it's also true for Linux (but the symlinking appears to be performed on both platforms).

I'll look into whether this is caused inside hoogle, or the hoogle.nix integration, but either way, it's more than concerning that the symlink causes a modified build.

**Comment by fiadliel** [comment]
Okay, I see at https://github.com/NixOS/nix/pull/3212 that it's known that the symlink approach is impure. For now, we can either stop building hoogle databases with this, or make a symlink from /opt/nix to /nix on other machines (where they use the volume approach).

This ticket may still have value to you, as it's a concrete example of impurities caused by the symlink approach in haskell builds.

**Comment by domenkozar** [comment]
I'd like to move away from symlink approach, but I'm not sure upstream has come to a better solution yet. Maybe @LnL can jump in :)

**Comment by LnL7** [comment]
Yeah, I updated that pr to create an apfs volume. Take a look  at create-darwin-volume.sh.

**Comment by domenkozar** [comment]
Could someone test with:

```
- uses: cachix/install-nix-action@releases/v7
```

before I make a release fixing this?

cc @nomeata

**Comment by fiadliel** [comment]
@domenkozar It installed and worked correctly for me. I don't know whether this might be useful to add, but it probably wouldn't hurt (no idea if Spotlight is running on the build machines):
`mdutil -i off /nix`
(as found at https://github.com/NixOS/nix/issues/2925#issuecomment-543466181)

In any case, thanks a lot for working on this!

**Comment by nomeata** [comment]
Yes, works here as well. Thanks!

**Comment by domenkozar** [comment]
Don't forget to switch to `@v7` once it's released, hopefully today or tomorrow.

**Comment by domenkozar** [comment]
Released `v7`
