### ISSUE TITLE
Installing Nix using Rosetta on macOS arm64

### ISSUE THREAD

**Issue by runeksvendsen** [cachix/install-nix-action#219]
On my personal laptop (MacBook M1) I have installed Nix using Rosetta in order to avoid all the broken arm64 packages for macOS. This is working great.

I would like to do the same in CI. However, I see no way to run the Nix installer using Rosetta — by prefixing the installation command with `arch -arch x86_64`.

How can I do this?

**Comment by sandydoo** [comment]
Nix has an option to override the `system` in `nix.conf`. There really is no need to install an x86 build of Nix for this.

For CI:

```yaml
extra_nix_config: |
  system = x86_64-darwin
```
