### ISSUE TITLE
Nix flakes support

### ISSUE THREAD

**Issue by zimbatm** [cachix/install-nix-action#34]
It would be great if it was possible to pin what version of nix is being installed, and then be able to install the nix flakes edition through this mechanism.

I think that the nix publishing needs to be extended to also publish install scripts for the flakes branch first.

**Comment by domenkozar** [comment]
That's doable via `install_url` option, but you'd have to generate the installer script.

If we'd use Cachix on github.com/NixOS/nix I would be able to get github actions to generate installer script for each PR.

The main challenge is that you need to first build binary tarball for platforms and then use a stable url to generate the installer.

**Comment by domenkozar** [comment]
See also https://github.com/cachix/cachix-action/issues/47

**Comment by domenkozar** [comment]
This is now supported in master. Ideally upstream would publish all Nix releases, but that's out of scope for this action.
