### ISSUE TITLE
Export or publish nixpkgs revision

### ISSUE THREAD

**Issue by acowley** [cachix/install-nix-action#35]
I apologize if this is documented, but I couldn't find it.

We're trying to use GitHub actions with a cron schedule to provide a rolling release of [nixos-rocm](http://github.com/nixos-rocm/nixos-rocm). We want a daily rebuild to pick up `nixos-unstable` advances, so we don't pin `nixpkgs` in our build. But then I'd like to report what revision of `nixpkgs` was used in the most recent build since I think we will bump into the free tier storage limits fairly quickly, meaning that we won't have many historical versions in the cache.

Is there an existing way of having a badge or something that lists the specific revision the action picked up with its channel setting?

**Comment by domenkozar** [comment]
That's a good idea - https://github.com/cachix/cachix-action/issues/46

**Comment by acowley** [comment]
Ack, and I spent some time deciding which repo to open the issue with. The `echo` is great, and I should add that to my workflow. Do you know how to better surface that information for users? I thought of the badge thing, but really I just want something more visible than clicking through the main GitHub web UI. I’ll dig to see if the latest logs are accessible in some easy way.

**Comment by domenkozar** [comment]
The action could put the version in the output, then you could use that to generate an image with something like https://github.com/marketplace/actions/bring-your-own-badge. That's the best I can think of :)
