### ISSUE TITLE
Retries?

### ISSUE THREAD

**Issue by cprussin** [cachix/install-nix-action#36]
I've noticed the install-nix-action failing occasionally with logs like:

```
Run cachix/install-nix-action@v10
  with:
    nix_path: nixpkgs=channel:nixos-20.03
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to nixos.org port 443: Connection refused
```

See for example https://github.com/cprussin/nixjs/runs/818847845.

Would it be a good idea to add something like `--retry 5` around the curl command here https://github.com/cachix/install-nix-action/blob/master/lib/install-nix.sh#L16?

**Comment by cprussin** [comment]
cc @domenkozar , I'd be happy to open a PR if you want

**Comment by domenkozar** [comment]
Please do! Make sure SSL errors are covered :)
