### ISSUE TITLE
Act does no support sudo

### ISSUE THREAD

**Issue by gianarb** [cachix/install-nix-action#42]
Hello, I am using Act to test GitHub actions locally. It is a very nice tool 
https://github.com/nektos/act

This action does not work there because the installation process requires `sudo` and `act` runs inside a container.

To reproduce this issue you can install act, and use it to run locally a workflow that uses this action.

**Comment by gianarb** [comment]
I think this is not a nix issue or action issue

**Comment by cdc-Hitesh** [comment]
Any progress/help on this. I am stuck here. THanks

**Comment by domenkozar** [comment]
@cdc-Hitesh could you elaborate?

**Comment by cdc-Hitesh** [comment]
@domenkozar 
My job looks like this: 
`integrate:
    runs-on: ubuntu-latest
    shell: bash
    steps:
    - name: ts-project
      uses: actions/checkout@v2
      with:
        path: main
    - uses: cachix/install-nix-action@v10
      with:
       nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        echo "hello"`

When I do `act -j integrate`.
This is the error I run into:
`[integration_test_poc/integrate] ⭐  Run cachix/install-nix-action@v11
[integration_test_poc/integrate]   ☁  git clone 'https://github.com/cachix/install-nix-action' # ref=v11
[integration_test_poc/integrate]   🐳  docker cp src=/Users/hitesh.goel/.cache/act/cachix-install-nix-action@v11 dst=/actions/
| /actions/cachix-install-nix-action@v11/lib/install-nix.sh: line 6: sudo: command not found
| child_process.js:644
|     throw err;
|     ^
| 
| Error: Command failed: /actions/cachix-install-nix-action@v11/lib/install-nix.sh
|     at checkExecSyncError (child_process.js:623:11)
|     at Object.execFileSync (child_process.js:641:15)
|     at Object.<anonymous> (/actions/cachix-install-nix-action@v11/lib/main.js:4:17)
|     at Module._compile (internal/modules/cjs/loader.js:776:30)
|     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
|     at Module.load (internal/modules/cjs/loader.js:643:32)
|     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
|     at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
|     at internal/main/run_main_module.js:17:11 {
|   status: 127,
|   signal: null,
|   output: [ null, null, null ],
|   pid: 28,
|   stdout: null,
|   stderr: null
| }`

I tried running with: `act -j integrate  -P ubuntu-latest=nektos/act-environments-ubuntu:18.04 -v`
then I run into:
`integration_test_poc/integrate]   ❓  ::group::Getting Git version info
| Working directory is '/github/workspace/chain-main'
[integration_test_poc/integrate]   ❓  ::endgroup::
| The repository will be downloaded using the GitHub REST API
| To create a local Git repository instead, add Git 2.18 or higher to the PATH
| Determining the default branch
| Retrieving the default branch name
| request to https://api.github.com/repos/crypto-com/chain-main failed, reason: self signed certificate in certificate chain
| Waiting 18 seconds before trying again
| Retrieving the default branch name
| request to https://api.github.com/repos/crypto-com/chain-main failed, reason: self signed certificate in certificate chain
| Waiting 14 seconds before trying again
| Retrieving the default branch name
[integration_test_poc/integrate]   ❓  ::remove-matcher owner=checkout-git,::
[integration_test_poc/integrate]   ❗  ::error::request to https://api.github.com/repos/crypto-com/chain-main failed, reason: self signed certificate in certificate chain
[integration_test_poc/integrate]   ❌  Failure - Checkout chain-main repo
Error: exit with `FAILURE`: 1`

Any way out?

**Comment by domenkozar** [comment]
That seems to be a problem with certificates, not sure what's really going on

**Comment by domenkozar** [comment]
https://github.com/cachix/install-nix-action/releases/tag/v14 allows use of act now!

**Comment by Henry-Hiles** [comment]
I think this is now using sudo again, right? I'm having issues running on an act runner.
