### ISSUE TITLE
How to specify commit for nixpkgs?

### ISSUE THREAD

**Issue by bbarker** [cachix/install-nix-action#51]
Instead of specifying a channel, how might one go about specifying a commit (e.g. the commented line)?

        nix_path: nixpkgs=channel:nixos-20.09
        # nix_path: nixpkgs=channel:0b8799ecaaf0dc6b4c11583a3c96ca5b40fcfdfb # in 20.09, Oct 9 2020

**Comment by bbarker** [comment]
I suppose I could just use a nix-shell expression that pins nixpkgs in the usual way - is this the intent?

**Comment by domenkozar** [comment]
https://nix.dev/reference/pinning-nixpkgs.html
