### ISSUE TITLE
Use build cache?

### ISSUE THREAD

**Issue by worldofgeese** [cachix/install-nix-action#54]
I have a very large derivation that takes 45 minutes or so to build. When commits hit setting off a rebuild it would be nice if a build cache could be leveraged to speed up build times. Is something like this possible?

**Comment by domenkozar** [comment]
Do you mean https://github.com/cachix/cachix-action or something else?

**Comment by worldofgeese** [comment]
That is exactly what I meant. Apologies for this wasteful issue. Maybe a mention of cachix-action could be written on the install-nix action page, to avoid such questions in the future. Thank you!

**Comment by domenkozar** [comment]
It's mentioned in https://github.com/cachix/install-nix-action#usage
