### ISSUE TITLE
Flakes example no longer works

### ISSUE THREAD

**Issue by Mic92** [cachix/install-nix-action#61]
It still uses `cachix/install-nix-action@v11` but also upgrading to `v12` does not help:

https://github.com/Mic92/nix-update/pull/30/checks?check_run_id=1478992110

```
  nix build
  shell: /bin/bash -e {0}
error: --- SysError --- nix
getting attributes of path '/nix/store/550xkq18mh8a6xgpnard55rjqxa9zmlc-source': No such file or directory
(use '--show-trace' to show detailed location information)
Error: Process completed with exit code 1.
```

Sorry I have not investigated deeply what is going on here...
Does it work for someone else?

**Comment by domenkozar** [comment]
I'm not sure as I'm not using Flakes, but a new installer should be generated from recent master as the one linked in README is quite buggy. See #48
