### ISSUE TITLE
--daemon-user-count 4?

### ISSUE THREAD

**Issue by colinxs** [cachix/install-nix-action#79]
Is there a reason for `--daemon-user-count 4` being including in the install flags? If not, could you either remove it or change it to the installer's default of 32? I have an update script that updates 100+ packages at once in parallel (with 32 threads) and it's erroring out because there's not enough builders.

**Comment by domenkozar** [comment]
That should definitely be a setting one can override. 

It should default to a number of cores, and also set then `maxJobs`.

**Comment by domenkozar** [comment]
@colinxs are you running your own github runners?

**Comment by colinxs** [comment]
Nope, but since it's mostly IO Bound the two cores github provides is enough.

**Comment by domenkozar** [comment]
Agreed - making the user count configurable sounds good to me.

**Comment by nomeata** [comment]
I am hitting this due to 
```
error: all build users are currently in use; consider creating additional users and adding them to the 'nixbld' group
```
so making this configurable would be nice.

**Comment by domenkozar** [comment]
@nomeata self hosted runners?

**Comment by nomeata** [comment]
No, github runners. A colleage claimed that `--max-jobs 10` would help with our workload (I have my doubts as well on these rather weak machines). Still, might be nice to configure this. Or alternatively wait for 2.4 which will have https://github.com/NixOS/nix/pull/3564.

**Comment by dysinger** [comment]
I moved my build from my fork of this repo to this repo and this bit me again. I launched 4x (8 cpu x 32gb ram) and they fail to build with "error: all build users are currently in use; consider creating additional users and adding them to the 'nixbld' group"

**Comment by domenkozar** [comment]
How about defaulting to `2 * cpu cores` and having an option to override it?

**Comment by domenkozar** [comment]
Released https://github.com/cachix/install-nix-action/releases/tag/v14

**Comment by dysinger** [comment]
On fresh Ubuntu LTS:

![image](https://user-images.githubusercontent.com/447/132894292-a8702250-7c86-416d-af92-45ef18994f56.png)

**Comment by dysinger** [comment]
Workaround 
![image](https://user-images.githubusercontent.com/447/132895242-94a7015b-599f-4335-aede-3d8f820f47b4.png)

**Comment by dysinger** [comment]
The workaround is just to add another step to install python first

**Comment by domenkozar** [comment]
Huh, no python installed on Linux!

Not sure I can really fix this kind of thing as self-hosted runners will just always contain different set of software compared to hosted VMs. 

Maybe it would be better to just rely on coreutils + kernel api.
