### ISSUE TITLE
v13 began failing: /dev/fd/63: 1: 404: not found (Flakes)

### ISSUE THREAD

**Issue by srid** [cachix/install-nix-action#83]
https://github.com/srid/emanote/runs/2896864995

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
installer options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve --daemon --daemon-user-count 4 --no-channel-add --darwin-use-unencrypted-nix-store-volume --nix-extra-conf-file /tmp/nix.conf
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    108      0 --:--:-- --:--:-- --:--:--   108
/dev/fd/63: 1: 404: not found
child_process.js:642
    throw err;
    ^

Error: Command failed: /home/runner/work/_actions/cachix/install-nix-action/v13/lib/install-nix.sh
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.<anonymous> (/home/runner/work/_actions/cachix/install-nix-action/v13/lib/main.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 1623,
  stdout: null,
  stderr: null
}
```

My repo is following instructions from https://github.com/cachix/install-nix-action#usage-with-flakes

**Comment by srid** [comment]
Fixed on my repo in https://github.com/srid/emanote/commit/98f0b6c5c92e79e44af1d8718eb7a1b604f8c28a 

by following the "To install Nix from any commit..." part of https://github.com/cachix/install-nix-action#usage-with-flakes

**Comment by hlolli** [comment]
I used your revision @srid worked once, now, again same error.

**Comment by tbidne** [comment]
Noticed the same issue, @srid's revision is working for me so far (I have run it a couple times, given @hlolli's comment).

**Comment by dhess** [comment]
Also getting this. @domenkozar I assume this is because the previous installer URL https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install is returning a 404. Any way to recover it?

**Comment by domenkozar** [comment]
Looking into this!

**Comment by domenkozar** [comment]
Seems like my personal GC limit was too low. 

I'll try to recover it, meanwhile use https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install

**Comment by domenkozar** [comment]
GitHub Actions doesn't allow searching through their logs yet, does anyone have the installer somewhere locally? 

Otherwise finding the commit might involve a bit of scripting.

**Comment by domenkozar** [comment]
It seems that GitHub Actions logs also expired. Unless someone has the installer cached locally, there won't be a way to recover it.

The good news is that this makes a good lesson on how I should implement GC roots, to allow metadata like git revision. 

I'll also implement notifications when GC limit is too low.

**Comment by dhess** [comment]
Well, at least you used the `nixos-nix-install-tests` domain name for the flake installers, which implies that this is just a test and things may break :)

**Comment by domenkozar** [comment]
The culprit was that the `/serve/` endpoint didn't update the last accessed time (since that endpoint was never even used widely before the installer work).

It now correctly tracks that and I've increased my GC limit by 4x.

I'm truly sorry that this bug has hit you all.
