### ISSUE TITLE
occasional failures during setup

### ISSUE THREAD

**Issue by cpcloud** [cachix/install-nix-action#91]
I am seeing some (seemingly infrequent) errors during the setup of nix: https://github.com/ibis-project/ibis/runs/3497522732

![image](https://user-images.githubusercontent.com/417981/131877788-2f4ab9e1-496e-40d4-ba0d-17831ed1322e.png)

I'm not sure what's happening here, but I've seen a similar error that also occurred today: https://github.com/cpcloud/ibis/runs/3496144019

![image](https://user-images.githubusercontent.com/417981/131878128-4716a961-388e-4810-876f-bf306e4a4a33.png)

**Comment by cpcloud** [comment]
Saw another strange failure: https://github.com/cpcloud/ibis/runs/3500901151?check_suite_focus=true

![image](https://user-images.githubusercontent.com/417981/131926234-494291ed-3cc7-4ec2-ab3c-c37a219b3def.png)

**Comment by domenkozar** [comment]
The first error is most likely a networking issue, not sure there's an easy fix.

The second error is https://github.com/NixOS/nix/issues/3605

The last error is likely a bug in your code, you're importing `<nixpkgs>` while expecting to use a channel syntax.

**Comment by CohenCyril** [comment]
> The first error is most likely a networking issue, not sure there's an easy fix.

I'm having this one a lot. Isn't it possible to detect network failures and retry? (with a configurable number of attempts)

**Comment by domenkozar** [comment]
@CohenCyril how often does it happen? I could provide a script to debug and see what's going on, but it seems like the output gets cut prematurely.

**Comment by CohenCyril** [comment]
> @CohenCyril how often does it happen? I could provide a script to debug and see what's going on, but it seems like the output gets cut prematurely.

Our piplines are getting big now (5 * 80ish jobs), and every day I need to relaunch at least one or two pipelines (github actions provides no way to retry individual jobs so I need to restart a full pipeline every time this happens) because of this particular error.

**Comment by domenkozar** [comment]
@CohenCyril could you try using https://github.com/cachix/install-nix-action/pull/105 and let's see if and how it breaks?

**Comment by CohenCyril** [comment]
> @CohenCyril could you try using #105 and let's see if and how it breaks?

I will try. Thanks.

**Comment by domenkozar** [comment]
The first error is fixed, the rest are either Nix bugs or bugs in user code. Thanks for the report!
