### ISSUE TITLE
buildInputs are not available in devShell after issuing ´nix develop´ command

### ISSUE THREAD

**Issue by RCoeurjoly** [cachix/install-nix-action#92]
I am testing Python packages using poetry on nix.

For each package, I want to enter into a devShell with poetry, and install that package using poetry.

After `nix develop`, poetry is not found. Locally it works.

Is the state erased after running a command in GitHub actions?

flake:
https://github.com/RCoeurjoly/nix-poetry-testing/blob/main/flake.nix

Job:
https://github.com/RCoeurjoly/nix-poetry-testing/runs/3528313983?check_suite_focus=true

**Comment by domenkozar** [comment]
Hey! This is not a support channel for flakes, try https://github.com/NixOS/nixpkgs#community
