### ISSUE TITLE
macos-11 unsupported?

### ISSUE THREAD

**Issue by miuirussia** [cachix/install-nix-action#96]
As described, macos-latest will be upgraded to Big Sur (macos-11) (https://github.com/actions/virtual-environments/issues/4060). I upgraded my workflow to macos-11 (for testing) and then get error:

![image](https://user-images.githubusercontent.com/1270028/134222761-10e3915e-5dd2-47cb-8e5a-e13bf5bf6bd4.png)

You can see full log here:

https://github.com/miuirussia/nix-flake-env/runs/3666559886?check_suite_focus=true

**Comment by domenkozar** [comment]
You need the latest Nix from master.

**Comment by miuirussia** [comment]
It doesn't pass the tests

**Comment by domenkozar** [comment]
Do you mean CI? It has a flaky test on macOS.

**Comment by miuirussia** [comment]
Yes, here: https://hydra.nixos.org/jobset/nix/master

I use automatic nix install script update: https://github.com/miuirussia/nix-unstable-installer, that updates, when evaluation of jobset https://hydra.nixos.org/jobset/nix/master is success

**Comment by miuirussia** [comment]
Maybe problem here:   sudo mdutil -i off /nix

**Comment by domenkozar** [comment]
Latest commit succeeds: https://github.com/NixOS/nix/commit/362d8f925eae95f1feb912ada7e401c56d6f7398

**Comment by miuirussia** [comment]
But on hydra not succeed: https://hydra.nixos.org/jobset/nix/master because of this, the binaries were not released and

**Comment by miuirussia** [comment]
And, as I understand from log: https://github.com/miuirussia/nix-flake-env/runs/3666559886?check_suite_focus=true, installer script worked correctly without errors. Problem in `install-nix.sh` from this action

**Comment by domenkozar** [comment]
This was fixed in https://github.com/NixOS/nix/pull/5281

I've changed the recommended installer in https://github.com/cachix/install-nix-action/commit/791347c66b961d5b142efa10228e486a372a6fb8

**Comment by shonfeder** [comment]
We are hitting the same problem, despite using the latest installer recommended: https://github.com/informalsystems/apalache/runs/3908711785?check_suite_focus=true#step:4:927
